### ISSUE TITLE
comment error: platform-specific comments don't match platforms being built

### ISSUE THREAD

**Issue by ericsebesta** [MrSimbax/pong-x#15]
Looks like a copy/paste error between mac and linux, super minor - [here](https://github.com/MrSimbax/pong-x/blob/master/TravisScripts/build.sh#L56-L60).

I found this while looking for anyone else using Travis-CI for unity builds. Good stuff!

**Comment by MrSimbax** [comment]
I'm actually using slightly modified scripts from this great tutorial https://jonathan.porta.codes/2015/04/17/automatically-build-your-unity3d-project-in-the-cloud-using-travisci-for-free/

**Comment by ericsebesta** [comment]
Yup, I'm working off the same tutorial.
